name: Render and Deploy Quarto Site

on:
  push:
    branches: [main]          # whenever you push new changes
  schedule:
    - cron: "0 13 * * *"      # every day at 13:00 UTC (adjust as you like)
  workflow_dispatch:           # allows manual trigger from GitHub

jobs:
  build-deploy:
    runs-on: ubuntu-latest

    permissions:
      contents: write
      pages: write
      id-token: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up R
        uses: r-lib/actions/setup-r@v2

      - name: Install R packages
        run: |
          Rscript -e 'install.packages(c("rStrava", "dplyr", "lubridate", "readr", "ggplot2", "quarto"))'

      - name: Update Strava data
        env:
          STRAVA_APP_NAME: ${{ secrets.STRAVA_APP_NAME }}
          STRAVA_CLIENT_ID: ${{ secrets.STRAVA_CLIENT_ID }}
          STRAVA_CLIENT_SECRET: ${{ secrets.STRAVA_CLIENT_SECRET }}
        run: |
          Rscript R/update_strava_data.R

      - name: Set up Quarto
        uses: quarto-dev/quarto-actions/setup@v2

      - name: Render site
        run: |
          quarto render

      - name: Publish to GitHub Pages
        uses: quarto-dev/quarto-actions/publish@v2
        with:
          target: gh-pages
