name: Update Strava Data

on:
  schedule:
    - cron: "0 12 * * *"   # every day at 12:00 UTC
  workflow_dispatch:

jobs:
  update:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up R
        uses: r-lib/actions/setup-r@v2

      - name: Install dependencies
        run: |
          Rscript -e 'install.packages(c("rStrava", "dplyr", "lubridate", "readr"))'

      - name: Run Strava update
        env:
          STRAVA_APP_NAME: ${{ secrets.STRAVA_APP_NAME }}
          STRAVA_CLIENT_ID: ${{ secrets.STRAVA_CLIENT_ID }}
          STRAVA_CLIENT_SECRET: ${{ secrets.STRAVA_CLIENT_SECRET }}
        run: |
          Rscript R/update_strava_data.R

      - name: Commit and push updated data
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "actions@github.com"
          git add data/strava_activities.csv
          git commit -m "Auto-update Strava data" || echo "No changes to commit"
          git push
